import { getJson } from './http';
import type { NormalizedContent, ProviderResult } from './types';

const graph='https://graph.threads.net';
type ThreadPost={id:string;text?:string;timestamp:string;permalink?:string;media_type?:string};
type Insight={name:string;values?:Array<{value:number}>;total_value?:{value:number}};
function value(data:Insight[],name:string){const item=data.find(x=>x.name===name);const v=item?.total_value?.value??item?.values?.at(-1)?.value;return typeof v==='number'?v:0}
async function insights(id:string,token:string){try{return (await getJson<{data:Insight[]}>(`${graph}/${id}/insights`,{metric:'views,likes,replies,reposts,quotes,shares'},token)).data}catch{return []}}
export async function syncThreads(token:string):Promise<ProviderResult>{const warnings:string[]=[];let followers=0;try{const account=await getJson<{data:Insight[]}>(`${graph}/me/threads_insights`,{metric:'followers_count'},token);followers=value(account.data,'followers_count')}catch{/* account insight can be unavailable while post sync still works */}const response=await getJson<{data:ThreadPost[]}>(`${graph}/me/threads`,{fields:'id,text,timestamp,permalink,media_type',limit:100},token);const contents:NormalizedContent[]=[];for(const post of response.data){const ins=await insights(post.id,token);const likes=value(ins,'likes'),comments=value(ins,'replies'),reposts=value(ins,'reposts'),quotes=value(ins,'quotes'),shares=value(ins,'shares'),views=value(ins,'views');contents.push({id:`threads-${post.id}`,nativeContentId:post.id,platform:'Threads',type:'Threads Post',title:(post.text||'Threads 貼文').slice(0,100),caption:post.text||'',publishedAt:post.timestamp,views,impressions:views,reach:views,engagement:likes+comments+reposts+quotes+shares,likes,comments,shares:shares+reposts,saves:0,clicks:0,messages:0,campaignId:'unassigned',campaignName:'尚未歸類',confidence:'low',reviewStatus:'suggested',url:post.permalink||'',permalink:post.permalink||null,lastSource:'threads-api',lastUpdatedAt:new Date().toISOString()})}if(!response.data.length)warnings.push('Threads API 未回傳內容。');return{platform:'Threads',contents,account:{followers,reach:contents.reduce((s,x)=>s+x.reach,0),views:contents.reduce((s,x)=>s+x.views,0),engagement:contents.reduce((s,x)=>s+x.engagement,0)},warnings}}
